import { Scholarship } from "./types";

const generateId = () => Math.random().toString(36).substring(2, 10);

const dateIso = new Date().toISOString();

export const mockNationalScholarships: Partial<Scholarship>[] = [
  {
    title: "AICTE Pragati Scholarship for Girls",
    provider: "AICTE, Government of India",
    amount: "₹50,000/year",
    deadline: "2026-10-31",
    location: "India",
    category: "Technology",
    description: "Scholarship for girl students pursuing technical education.",
    url: "https://www.aicte-pragati-saksham-gov.in/",
    min_gpa: 7.0,
    eligible_levels: ["Undergraduate (Bachelor's)"],
    eligible_genders: "Female",
    income_level: "Low",
    min_age: 18,
    max_age: 25,
    eligible_nationalities: "India",
  },
  {
    title: "National Means-cum-Merit Scholarship (NMMS)",
    provider: "Ministry of Education",
    amount: "₹12,000/year",
    deadline: "2026-11-15",
    location: "India",
    category: "STEM",
    description: "Financial assistance to meritorious students of economically weaker sections.",
    url: "https://scholarships.gov.in/",
    min_gpa: null,
    eligible_levels: [],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: null,
    max_age: null,
    eligible_nationalities: "All",
  },
  {
    title: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
    provider: "Department of Science and Technology",
    amount: "₹5,000 - ₹7,000/month",
    deadline: "2026-08-25",
    location: "India",
    category: "STEM",
    description: "National fellowship program for students in Basic Sciences.",
    url: "http://kvpy.iisc.ernet.in/",
    min_gpa: 8.0,
    eligible_levels: ["High School", "Undergraduate (Bachelor's)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: 16,
    max_age: 22,
    eligible_nationalities: "India",
  },
  {
    title: "Post Matric Scholarship for Minorities",
    provider: "Ministry of Minority Affairs",
    amount: "₹10,000/year",
    deadline: "2026-09-30",
    location: "India",
    category: "Other",
    description: "Financial assistance for minority community students.",
    url: "https://scholarships.gov.in/",
    min_gpa: 5.0,
    eligible_levels: ["Undergraduate (Bachelor's)", "Graduate (Master's)"],
    eligible_genders: "Any",
    income_level: "Low",
    min_age: null,
    max_age: null,
    eligible_nationalities: "India",
  },
  {
    title: "HDFC Bank Educational Crisis Scholarship",
    provider: "HDFC Bank",
    amount: "Up to ₹75,000",
    deadline: "2026-07-15",
    location: "India",
    category: "Other",
    description: "Support for students whose families are facing personal or economic crisis.",
    url: "https://www.hdfcbank.com/personal/about-us/csr/educational-crisis-scholarship-support",
    min_gpa: 6.0,
    eligible_levels: ["Undergraduate (Bachelor's)"],
    eligible_genders: "Any",
    income_level: "Low",
    min_age: 18,
    max_age: 25,
    eligible_nationalities: "India",
  },
  {
    title: "Reliance Foundation Undergraduate Scholarships",
    provider: "Reliance Foundation",
    amount: "Up to ₹2,00,000",
    deadline: "2026-10-15",
    location: "India",
    category: "STEM",
    description: "Merit-cum-means scholarship for undergraduate students across India.",
    url: "https://scholarships.reliancefoundation.org/",
    min_gpa: 7.5,
    eligible_levels: ["Undergraduate (Bachelor's)"],
    eligible_genders: "Any",
    income_level: "Middle",
    min_age: 18,
    max_age: 24,
    eligible_nationalities: "India",
  },
  {
    title: "Tata Trusts Medical and Healthcare Scholarships",
    provider: "Tata Trusts",
    amount: "Varies",
    deadline: "2026-12-01",
    location: "India",
    category: "Medicine",
    description: "For students enrolled in medical and healthcare degree programs.",
    url: "https://www.tatatrusts.org/our-work/individual-grants-initiative/education-grants",
    min_gpa: 8.0,
    eligible_levels: ["Undergraduate (Bachelor's)", "Graduate (Master's)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: null,
    max_age: null,
    eligible_nationalities: "India",
  },
];

export const mockInternationalScholarships: Partial<Scholarship>[] = [
  {
    title: "Chevening Scholarships",
    provider: "UK Government",
    amount: "Full Tuition + Living Expenses",
    deadline: "2026-11-05",
    location: "United Kingdom",
    category: "Leadership",
    description: "Fully-funded scholarships to study for a master's degree in the UK.",
    url: "https://www.chevening.org/",
    min_gpa: 7.0,
    eligible_levels: ["Graduate (Master's)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: 21,
    max_age: 40,
    eligible_nationalities: "All",
  },
  {
    title: "Fulbright Foreign Student Program",
    provider: "US Department of State",
    amount: "Full Tuition + Stipend",
    deadline: "2026-10-15",
    location: "United States",
    category: "Other",
    description: "Enables graduate students, young professionals, and artists from abroad to study and conduct research in the US.",
    url: "https://foreign.fulbrightonline.org/",
    min_gpa: 7.5,
    eligible_levels: ["Graduate (Master's)", "Doctoral (PhD)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: 21,
    max_age: null,
    eligible_nationalities: "All",
  },
  {
    title: "Erasmus Mundus Joint Masters Scholarships",
    provider: "European Union",
    amount: "Up to €25,000",
    deadline: "2026-01-15",
    location: "Europe (Multiple)",
    category: "Other",
    description: "Prestigious, integrated, international study programmes globally.",
    url: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
    min_gpa: null,
    eligible_levels: [],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: null,
    max_age: null,
    eligible_nationalities: "All",
  },
  {
    title: "MEXT Japanese Government Scholarship",
    provider: "Ministry of Education, Japan",
    amount: "Full Tuition + ¥144,000/month",
    deadline: "2026-05-30",
    location: "Japan",
    category: "STEM",
    description: "Scholarships for international students who wish to study at Japanese universities.",
    url: "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm",
    min_gpa: 8.5,
    eligible_levels: ["Undergraduate (Bachelor's)", "Graduate (Master's)", "Doctoral (PhD)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: 18,
    max_age: 35,
    eligible_nationalities: "All",
  },
  {
    title: "DAAD Scholarships for Developing Countries",
    provider: "DAAD Germany",
    amount: "Full Tuition + €934/month",
    deadline: "2026-09-01",
    location: "Germany",
    category: "Technology",
    description: "Postgraduate scholarships for professionals from developing countries.",
    url: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    min_gpa: 7.0,
    eligible_levels: ["Graduate (Master's)", "Doctoral (PhD)"],
    eligible_genders: "Any",
    income_level: "Low",
    min_age: 22,
    max_age: null,
    eligible_nationalities: "All",
  },
  {
    title: "Gates Cambridge Scholarships",
    provider: "Gates Cambridge Trust",
    amount: "Full Tuition + £20,000/year",
    deadline: "2026-10-11",
    location: "United Kingdom",
    category: "STEM",
    description: "Full-cost scholarships for a postgraduate degree in any subject available at the University of Cambridge.",
    url: "https://www.gatescambridge.org/",
    min_gpa: 9.0,
    eligible_levels: ["Graduate (Master's)", "Doctoral (PhD)"],
    eligible_genders: "Any",
    income_level: "Any",
    min_age: 21,
    max_age: null,
    eligible_nationalities: "All",
  },
];

export const getStaticMockScholarships = (): Scholarship[] => {
  const pool = [...mockNationalScholarships, ...mockInternationalScholarships];
  return pool.map((t, idx) => ({
    ...t,
    id: `mock-static-${idx}`,
    created_at: dateIso,
    featured: Math.random() > 0.8,
    url: t.url || "#",
    min_gpa: t.min_gpa ?? null,
    eligible_levels: t.eligible_levels ?? null,
    eligible_genders: t.eligible_genders ?? "Any",
    income_level: t.income_level ?? "Any",
    min_age: t.min_age ?? null,
    max_age: t.max_age ?? null,
    eligible_nationalities: t.eligible_nationalities ?? "All"
  } as Scholarship));
};

export const generateRandomScholarship = (pool: Partial<Scholarship>[]) => {
  const template = pool[Math.floor(Math.random() * pool.length)];
  return {
    ...template,
    id: `live-${generateId()}`,
    created_at: new Date().toISOString(),
    featured: Math.random() > 0.8,
    url: template.url || "#",
    min_gpa: template.min_gpa ?? null,
    eligible_levels: template.eligible_levels ?? null,
    eligible_genders: template.eligible_genders ?? "Any",
    income_level: template.income_level ?? "Any",
    min_age: template.min_age ?? null,
    max_age: template.max_age ?? null,
    eligible_nationalities: template.eligible_nationalities ?? "All"
  } as Scholarship;
};
